### ISSUE TITLE
Issues With Custom Fields 

### ISSUE THREAD

**Issue by tobyhersey** [kgish/assembla-to-jira-migration#18]
Issues Mapping Custom Fields , have followed your Document and got to stage 10 Custom Fields but am unable to work it out , have added the Assembla Custom fields and assigned to screens but still get the error.

GOODBYE: Missing screens ids, ARGV1=screen_id1 and ARGV2=screen_id2 (see README.md).

How do i know which Fields are not being found / Added , if i run the ruby 11 script one or two ticket get created then i run into this

WARNING: Reformat markdown name='tmutton' => NOK
GOODBYE: POST https://redacted/rest/api/2/issue payload='{:create=>{}, :fields=>{:project=>{:id=>"10000"}, :summary=>"Spike: Dev Team - Posters for Room - Image Capture -1.5 Hrs", :issuetype=>{:id=>"10005"}, :assignee=>{:name=>"AlpaJ"}, :reporter=>{:name=>"chaupt"}, :priority=>{:name=>"Medium"}, :labels=>["assembla", "Dev-Team"], :description=>"...", :customfield_10017=>"2783", :customfield_10018=>"Done", :customfield_10019=>"11830243", :customfield_10022=>"2017-10-11"}}' => NOK (key='issuetype', reason='The issue type selected is invalid.')

**Comment by kgish** [comment]
Please have a look at the [Create Custom Fields](https://github.com/kgish/assembla-to-jira-migration#create-custom-fields) section of the README.md file.

You will need to run the following script from the command line:

```
$ ruby 10-jira_create_custom_fields.rb screen_id1 screen_id2
```

where the values of `screen_id1` and `screen_id2` are found by going to the 'Admin Screens' page and hovering your mouse over the 'Scrum Bug Screen Scheme' link and then the 'Scrum Default Screen Scheme' link respectively.

While hovering your mouse over a link, you should see in the bottom left corner a status message popping up (as shown in the screenshot in the section named above) with an URL looking something like this:

```
.../secure/admin/ConfigureFieldScreenScheme.jspa?id=10001
```

So assuming that `10001` is the id for the first screen and `10002` is the id of the second screen, the command above would be:

```
$ ruby 10-jira_create_custom_fields.rb 10001 10002
```

Of course, in your case the values of the id could be different.

Hope this helps.

**Comment by tobyhersey** [comment]
Thanks That has clear a few things up and allowed me to progress.

Also big thanks for creating and documenting your tool :)

**Comment by kgish** [comment]
It was my pleasure, glad to be of help and good luck!
