### ISSUE TITLE
shouldn't this line be checking for ARGV[0] > @attachments_total not @total_tickets

### ISSUE THREAD

**Issue by Romany-Saad** [kgish/assembla-to-jira-migration#22]
https://github.com/kgish/assembla-to-jira-migration/blob/881d9117e246492e71840ed323a779d1b817e402/14-jira_import_attachments.rb#L21

`
goodbye("Invalid arg='#{ARGV[0]}', cannot be greater than the number of tickets=#{@attachments_total}") if restart_offset > @attachments_total
`

**Comment by kgish** [comment]
That is correct:

```
goodbye("Invalid arg='#{ARGV[0]}', cannot be greater than the number of attachments=#{@attachments_total}") if restart_offset > @attachments_total
```

should be replaced after the line:
```
puts "Total attachments: #{@attachments_total}"
```
Can you create a pull request?

**Comment by Romany-Saad** [comment]
sorry i never wrote ruby before so didn't want to pollute your repo or providing a half solution
