### ISSUE TITLE
switch from Jira username to accountId?

### ISSUE THREAD

**Issue by simpixelated** [kgish/assembla-to-jira-migration#28]
As of June 15, 2018 onwards, Atlassian switched from using `username` to `accountId`.
https://confluence.atlassian.com/cloud/blog/2018/06/say-goodbye-to-usernames-in-atlassian-cloud

It might be enough for now to just add something to the readme that shows where to find your Jira username (since this took me awhile to figure out). You have to go https://your-company.atlassian.net/admin/users and click on a user to have it show in the URL. But who knows how long that will work.

**Comment by kgish** [comment]
Oh dear, this is a show-stopper. Thanks for the heads up!

**Comment by kgish** [comment]
Included in v1.5.
