### ISSUE TITLE
Connection timeout assembla

### ISSUE THREAD

**Issue by pkamps** [kgish/assembla-to-jira-migration#33]
Hi,

getting a lot of those errors:
GOODBYE: GET https://api.assembla.com/v1/spaces => NOK (Timed out connecting to server)

I tried it with curl on the same machine and the connection to assembla is working fine. I don't understand why RestClient::Request.execute has so much trouble connection to the assembla API.

**Comment by kgish** [comment]
Strange, please provide me with the curl command that succeeds (excluding the credential of course) as well as the .env settings you are using.

Ideally if you could set me up with a temporary test account, I can have a look at it myself.

**Comment by pkamps** [comment]
I replaced RestClient::Request.execute with httparty - works a little better but at some point I get connection issues. The command line curl:

curl -H "X-Api-Key: 123" -H "X-Api-Secret: 321" https://api.assembla.com/v1/spaces

always works.

I can now blame ruby or my VM setup. My next step is to try to the code on an amazon box. You can close this ticket - it doesn't look like it's related to your codebase.

**Comment by kgish** [comment]
Okay, good luck, When you resolve the issue, please record your findings here for future reference.

**Comment by pkamps** [comment]
Exporting from assembla works like a charm on an amazon box. I guess my VM was misconfigured. So this issue is really unrelated to your code.

**Comment by kgish** [comment]
Okay great, thanks for telling me.
