### ISSUE TITLE
Base 64 Encode not using Strict Encode; Authentication Failure

### ISSUE THREAD

**Issue by QlikChristinaJenks** [kgish/assembla-to-jira-migration#37]
Was trying to use the tool and was running across http 403 with my creds. Triple checked the creds and found no obvious issues, so I  printed the auth headers to the command line and compared the output known good auth headers. 

Turns out there were random \n newline characters thrown in. Dug into this a little bit, and apparently this is the expected behavior for the Base64.encode64 method and instead the strict_encode64 method should be used. (especially in my case when the admin user has a very very long password)

https://stackoverflow.com/questions/2620975/strange-n-in-base64-encoded-string-in-ruby

So, I changed the instances of this throughout the repo to use strict_encode64 and now everything works fine. 

Tried making a PR but it looks like I don't have permissions to. Anyway, the main areas that need to be changed are in these files:

assembla-to-jira-migration/lib/common.rb:
>   229  
>   230  base64_admin = if JIRA_SERVER_TYPE == 'hosted'
>   231:                  Base64.strict_encode64(JIRA_API_ADMIN_USER + ':' + JIRA_API_ADMIN_PASSWORD)
>   232                 else
>   233:                  # Base64.strict_encode64(JIRA_API_ADMIN_EMAIL + ':' + JIRA_API_ADMIN_PASSWORD)
>   234:                  Base64.strict_encode64(JIRA_API_ADMIN_EMAIL + ':' + JIRA_API_KEY).gsub(/\n/, '')
>   235                 end
>   236  
>   ...
>   245  def headers_user_login(user_login, user_email)
>   246    return JIRA_HEADERS_ADMIN if JIRA_SERVER_TYPE == 'hosted'
>   247:   { 'Authorization': "Basic #{Base64.strict_encode64(user_login + ':' + user_login)}", 'Content-Type': 'application/json; charset=utf-8' }
>   248:   # { 'Authorization': "Basic #{Base64.strict_encode64(user_email + ':' + JIRA_API_KEY).gsub(/\n/, '')}", 'Content-Type': 'application/json; charset=utf-8' }
>   249  end

assembla-to-jira-migration/lib/confluence-api.rb:
>   200    url = "#{API}/content/#{page_id}/child/attachment"
>   201    headers = {
>   202:     'Authorization': "Basic #{Base64.strict_encode64("#{EMAIL}:#{PASSWORD}")}",
>   203      'Content-Type': 'application/json; charset=utf-8',
>   204      'Accept': 'application/json',

**Comment by kgish** [comment]
Thanks for the heads up.

Was already using the following:
```
Base64.encode64(JIRA_API_ADMIN_EMAIL + ':' + JIRA_API_KEY).gsub(/\n/, '')
```
But in your case that wasn't sufficient.

**Comment by kgish** [comment]
Fixed, commit 594bd7ddf3d4cd191e7dbfe810ac2c2957fa6739

**Comment by QlikChristinaJenks** [comment]
Thanks a ton!

**Comment by QlikChristinaJenks** [comment]
@kgish , how can I contribute btw? I'm finding a few more things as I go along that could improve things a bit -- at least for Server. I don't have permissions to push branches so that I can make PRs.

**Comment by kgish** [comment]
@QlikChristinaJenks, this is a public repository so you should be able to contribute via pull requests, or am I missing something?
