### ISSUE TITLE
Sprints Not Closed As Expected Via REST Api (with workaround)

### ISSUE THREAD

**Issue by QlikChristinaJenks** [kgish/assembla-to-jira-migration#38]
Found a perplexing issue related to Atlassian's REST Api in Jira Server 8.1.3 -- not related to this script.

Haven't found a bug report on their side, but it does appear that when using the REST Api it doesn't actually update the sprint status. It will report the sprints are in the closed state, but you can see in the GUI that this isn't the case. Clearing Jira's internal caches doesn't change the result. 

This can be a problem when you have thousands of sprints imported (all active), as this will cause the Backlog page in Jira to take several minutes to load and otherwise be unusable.

So IF you run across this, then in the meanwhile you can use ScriptRunner or anything similar that can access the Java API to close all sprints (reopen them from the Reports tab in the Project Settings and/or feel free to modify the script as you please):

```groovy
import com.atlassian.jira.component.ComponentAccessor;
import com.atlassian.jira.user.ApplicationUser;
import com.onresolve.scriptrunner.runner.customisers.*;
import com.atlassian.greenhopper.service.rapid.view.*;
import com.atlassian.greenhopper.service.sprint.*;

@JiraAgileBean
SprintManager sprintManager

@JiraAgileBean
RapidViewService rapidViewService

String projectName = "Name Of Your Project"
String adminUsername = "admin-user"

ApplicationUser user = ComponentAccessor.getUserManager().getUserByKey(adminUsername)
def board = rapidViewService.findRapidViewsByName(user, projectName)
	.getValue()
	.get(0) // assumes the first result matches

def updateResults = sprintManager.getSprintsForView(board.getId(), EnumSet.of(Sprint.State.ACTIVE))
	.getValue()
	.collect { Sprint sprint ->
		Sprint updatedSprint = Sprint.builder(sprint).state(Sprint.State.CLOSED).build();
		sprintManager.updateSprint(updatedSprint)
}
```

**Comment by kgish** [comment]
Thanks for the tip. Rather than using the API for this, you can simply use the bulk edit tool on the Jira desktop, filter the relevant tickets by closed sprint.

For those less technical, this offers an easier doing this manually than having to run a low-level script.

**Comment by QlikChristinaJenks** [comment]
That is true, though it does not close sprints and affect the Backlog page. 
Worst case, I guess one could also change the default issue count in the URL when they load the page.
https://jira.example.com/secure/RapidBoard.jspa?rapidView=1234&projectKey=ABCD&view=planning.nodetail&**issueLimit=5**
